name: Build SPIFFS

on:
  push:
    branches:
      - '*'
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build SPIFFS
        run: |
         mkdir -p tools/spiffsgen
         mkdir -p build
         curl -fsSL https://raw.githubusercontent.com/espressif/esp-idf/v5.2.1/components/spiffs/spiffsgen.py -o tools/spiffsgen/spiffsgen.py
         python3 tools/spiffsgen/spiffsgen.py 1441792 $GITHUB_WORKSPACE/src/FreeVarioGauge/data build/FreeVarioGauge_data.spiffs 
         md5sum build/FreeVarioGauge_data.spiffs > build/FreeVarioGauge_data.spiffs.md5
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
           name: Archive SPIFFS image
           path: build/FreeVarioGauge_data.spiffs
           retention-days: 1